if(DEFINED VERSION_OVERRIDE AND NOT VERSION_OVERRIDE STREQUAL "")
    set(VERSION "${VERSION_OVERRIDE}")
    message(STATUS "Version: ${VERSION} (override)")
else()
    string(TIMESTAMP BUILD_TIME "%Y.%m.%d.%H%M")
    set(VERSION "v${BUILD_TIME}")
    message(STATUS "Version: ${VERSION}")
endif()
file(WRITE "${OUTPUT_FILE}" "#pragma once\n#define MOLINK_VERSION \"${VERSION}\"\n")
